---
- name: Install Docker and Apache on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    

    - name: Install Apache package
      yum:
        name: httpd
        state: present
      ignore_errors: yes

   

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes
