---
- name: Install Docker and Apache on localhost
  hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Install Docker package
      yum:
        name: docker
        state: present
      ignore_errors: yes

    - name: Install Apache package
      yum:
        name: httpd
        state: present
      ignore_errors: yes

    - name: Start and enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Start and enable Apache service
      service:
        name: httpd
        state: started
        enabled: yes
