---
- hosts: localhost
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Install Apache/HTTPD
      apt:
        name: apache2
        state: present
